# Generated by Django 4.2 on 2023-04-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type', models.CharField()),
                ('status', models.CharField()),
                ('title', models.CharField()),
                ('number_of_voters', models.CharField()),
                ('for_votes', models.CharField()),
                ('against_votes', models.CharField()),
                ('abstention_votes', models.CharField()),
                ('applicants', models.JSONField()),
                ('an_url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(unique=True)),
                ('first_name', models.CharField()),
                ('surname', models.CharField()),
                ('gender', models.CharField(blank=True, null=True)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField()),
                ('department_number', models.CharField()),
                ('district', models.CharField()),
                ('district_number', models.CharField()),
                ('mandate_start_date', models.DateField()),
                ('party_name', models.CharField()),
                ('party_acronym', models.CharField()),
                ('websites', models.JSONField()),
                ('email_addresses', models.JSONField()),
                ('addresses', models.JSONField()),
                ('associates', models.JSONField()),
                ('previous_mandates', models.JSONField()),
                ('profession', models.CharField()),
                ('twitter_name', models.CharField()),
                ('url_an', models.CharField()),
                ('id_an', models.CharField()),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deputy_party_acronym', models.CharField(blank=True, null=True)),
                ('vote', models.CharField()),
                ('party_vote', models.CharField()),
                ('delegated', models.BooleanField(default=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ballot')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.deputy')),
            ],
        ),
        migrations.AddIndex(
            model_name='deputy',
            index=models.Index(fields=['slug', 'slug'], name='tracker_dep_slug_ccb428_idx'),
        ),
    ]
